TrainMnist:
  name: 'Training'
  dataset:
   name: 'Mnist'
  model:
   batch_size: 16
   num_classes: 10

InferenceMnist:
 name: 'Inference'
 dataset:
  name: 'Mnist'
 model:
  batch_size: 1
 input-bind:
 - 'TrainMnist'

EvaluationIcnet:
 name: 'Evaluating'
 task:
  type: 'CLASSIFICATION'
  class_label:
  - '0'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
 measure:
 - 'CONFUSION-MATRIX'
 input-bind:
 - 'InferenceMnist'